### ISSUE TITLE
Add this Github to Ankiweb

### ISSUE THREAD

**Issue by ooker777** [muflax/beeminder-anki#7]
So that everybody can inform you easily if they find a bug or need to request
https://ankiweb.net/shared/info/3491889895
There is a long comment there

**Comment by muflax** [comment]
Sure, added a link. 

I don't read any comments over there, sorry.. The site has a very bad vibe. (I also don't use neither Beeminder nor Anki these days, so I'm not exactly maintaining either of this. :))
